version: "3.8"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_HTTP_LOG_ENABLED: "false"

      INFLUXDB_DB: "k6"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "password"

      INFLUXDB_WRITE_USER: "k6_writer"
      INFLUXDB_WRITE_USER_PASSWORD: "password"

      INFLUXDB_READ_USER: "grafana_reader"
      INFLUXDB_READ_USER_PASSWORD: "password"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    ulimits:
      nofile:
        soft: 65536
        hard: 65536